version: '2'
services:
  app:
    build: ./app
    image: app
    ports:
      - '80:8080'
  build:
    build: ./build
    image: ts-build
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
  centos-node:
    build:
      context: ./images
      dockerfile: centos-node
    image: centos-node