version: '2'
services:
  app:
    extends:
      file: common.yml
      service: app
    expose:
      - '8081'
    ports:
      - '3000:8080'
    volumes:
      - ./dist:/app/dist
    working_dir: /app
    command: node livereload/init.js
    depends_on:
      - centos-node
  build:
    extends:
      file: common.yml
      service: build
    command: npm run watch
    depends_on:
      - centos-node
  centos-node:
    extends:
      file: common.yml
      service: centos-node